[Eth.Miner]
#GasCeil = 140000000
GasFloor = 140000000
GasPrice = 1000000000 # This is an integer in the example, representing GWei.
Recommit = 10000000000 # This likely represents nanoseconds for a duration.
VoteEnable = true
#DelayLeftOver = 123456
# Deliberately omit DelayLeftOver to test if the default is applied.

[Node.LogConfig]
# time format for file logging
TimeFormat = "01-02|15:04:05.000"
